/* auto-generated by NAPI-RS */

const { existsSync, readdirSync } = require('fs')
const { join } = require('path')

const bindingsDir = join(__dirname, 'bindings')

const prefix = `wxml-parser-rs.${process.platform}-${process.arch}`

let nativeBinding = null
let loadError = null

// Exact match first, then ABI-suffixed variants (e.g. -gnu, -musl, -msvc)
const localCandidates = [`${prefix}.node`]

if (existsSync(bindingsDir)) {
  for (const name of readdirSync(bindingsDir)) {
    if (name.startsWith(prefix + '-') && name.endsWith('.node')) {
      localCandidates.push(name)
    }
  }
}

localCandidates.push('wxml-parser-rs.darwin-universal.node')

for (const name of localCandidates) {
  const p = join(bindingsDir, name)
  if (!existsSync(p)) continue
  try {
    nativeBinding = require(p)
    break
  } catch (e) {
    loadError = e
  }
}

if (!nativeBinding && loadError) {
  throw loadError
}

if (!nativeBinding) {
  throw new Error(
    `Failed to load native binding for ${process.platform}-${process.arch}. ` +
    `No matching .node file found in bindings/.`
  )
}

const { parse, parseForESLint } = nativeBinding

module.exports.parse = parse
module.exports.parseForESLint = parseForESLint
