/* auto-generated by NAPI-RS */

const { existsSync } = require('fs')
const { join } = require('path')

const bindingsDir = join(__dirname, 'bindings')

const localCandidates = [
  `wxml-parser-rs.${process.platform}-${process.arch}.node`,
  'wxml-parser-rs.darwin-universal.node',
]

let nativeBinding = null
let loadError = null

for (const name of localCandidates) {
  const p = join(bindingsDir, name)
  if (!existsSync(p)) continue
  try {
    nativeBinding = require(p)
    break
  } catch (e) {
    loadError = e
  }
}

if (!nativeBinding && loadError) {
  throw loadError
}

if (!nativeBinding) {
  throw new Error(
    `Failed to load native binding for ${process.platform}-${process.arch}. ` +
    `No matching .node file found in bindings/.`
  )
}

const { parse, parseForESLint } = nativeBinding

module.exports.parse = parse
module.exports.parseForESLint = parseForESLint
