/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Parse WXML and return a JSON string.
 * The JS side calls JSON.parse() to get the object.
 * This is much faster than returning serde_json::Value (avoids BTreeMap overhead)
 * and faster than building JS objects directly (too many FFI calls).
 */
export declare function parse(code: string): string
/**
 * Parse WXML for ESLint and return a JSON string.
 * The JS side calls JSON.parse() to get the object.
 */
export declare function parseForESLint(code: string): string
